export const ADD_TOURNAMENT = "ADD_TOURNAMENT";
export const UPDATE_TOURNAMENT = "UPDATE_TOURNAMENT";
export const DELETE_TOURNAMENT = "DELETE_TOURNAMENT";
export const REGISTER_PARTICIPANTS = "REGISTER_PARTICIPANTS";
export const FETCH_TOURNAMENT_LIST = "FETCH_TOURNAMENT_LIST";
